### ISSUE TITLE
【BUG】 输入新字段时候他文字总比其它原有的小

### ISSUE THREAD

**Issue by BoyceLig** [BoyceLig/ClashSinicizationTool#15]
![image](https://user-images.githubusercontent.com/49801599/189264216-0bdc6582-3d18-4a7c-9c15-838f7f236ea4.png)
### 采取措施：
- 可以保存时候默认invoke一下加载按钮
- 从根本找到问题来修改

**Comment by LightAPIs** [comment]
已提交 7a2551fe1faf18d2cea317e0358102a163995451 进行处理。
