### ISSUE TITLE
白塔加速网站挂了吗

### ISSUE THREAD

**Issue by shihunshi** [BoyceLig/ClashSinicizationTool#2]
之前充值的账号登录不了，重新注册也是一直跳转到空白页

**Comment by BoyceLig** [comment]
白塔加速的机场和OK加速合并了，你去OK加速注册一个账号，然后联系机场主吧注册账号给他，让他给你转套餐。
[联系机场主跳转](https://t.me/kuaizaiya)
[OK加速注册跳转](https://ok.okjiasu.com/auth/register?code=F9B0)
