### ISSUE TITLE
不要有“你已经汉化，请勿二次汉化”的提醒，因为我确实需要第二次汉化

### ISSUE THREAD

**Issue by zxmqq1234** [BoyceLig/ClashSinicizationTool#27]
刚更新CLASH的时候，翻译文档还没更新，是旧的翻译文档，但是能用着先。

现在过去了几天，翻译文档更新了，有最新版本的翻译内容了，我重新进行汉化，提示我“你已经汉化，请勿二次汉化”

但我的翻译内容只有上一个版本的翻译内容，我需要重新汉化一次

**Comment by LightAPIs** [comment]
先点击软件界面上的还原按钮就可以重新汉化了。

**Comment by zxmqq1234** [comment]
> 先点击软件界面上还原的按钮就可以重新汉化了。


但是还有一个逻辑会导致无法还原

因为我会下意识的点“解包”备份就会被覆盖了，这时候点“汉化”会提示无需汉化，点还原会说“散备份不存在或丢失，无法还原”

![image](https://user-images.githubusercontent.com/50194103/191146888-2d14699c-b950-4fc1-be2a-a459a52f8aac.png)
