### ISSUE TITLE
脚本被下载到系统目录C:\Windows\System32\里了

### ISSUE THREAD

**Issue by iamqiz** [BoyceLig/ClashSinicizationTool#33]
C:\Windows\System32\翻译脚本.txt

**Comment by LightAPIs** [comment]
那 `moment-with-CN.js` 和 `PathList.ini` 这些文件是在程序目录下，还是也被创建到 `C:\Windows\System32\` 目录里了？

**Comment by BoyceLig** [comment]
你运行文件放哪了

**Comment by iamqiz** [comment]
初次打开之后,我点击了用外部程序打开文件, 然后发现文件路径是 C:\Windows\System32\
其他两个文件也是, everything搜索结果如下

第一次打开之后:
![Snipaste_2023-01-28_22-00-38](https://user-images.githubusercontent.com/48077521/215270481-65c6a05b-55c4-4fea-91c9-059987fcc831.png)
![Snipaste_2023-01-28_22-00-58](https://user-images.githubusercontent.com/48077521/215270495-14e0e685-8595-4541-8634-8f1e91ab319e.png)

第二次打开之后: 
![Snipaste_2023-01-28_22-02-47](https://user-images.githubusercontent.com/48077521/215270575-cfd1ed23-9803-457b-a754-5d69ab1fef5e.png)
![Snipaste_2023-01-28_22-03-10](https://user-images.githubusercontent.com/48077521/215270592-2876f443-3310-4243-864e-ad10393c293e.png)
![Snipaste_2023-01-28_22-03-27](https://user-images.githubusercontent.com/48077521/215270606-c7ffc31f-204e-4968-9218-28eb458f11c6.png)

![Snipaste_2023-01-28_22-06-13](https://user-images.githubusercontent.com/48077521/215270762-a3ddd810-a5c4-4f19-bca5-30650eabfabc.png)

**Comment by BoyceLig** [comment]
运行文件的路径变过么

**Comment by iamqiz** [comment]
没有 

> 运行文件的路径变过么

**Comment by BoyceLig** [comment]
@LightAPIs  看起来像系统问题
